/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import domain.Komponenta;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import repository.Ponuda;

/**
 *
 * @author Cartman
 */
public class FrmTabelarniPrikazPonude extends javax.swing.JPanel {

    /**
     * Creates new form FrmTabelarniPrikazPonude
     */
    public FrmTabelarniPrikazPonude() {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePonuda = new javax.swing.JTable();

        tablePonuda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePonuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePonuda;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        fillTablePonuda();
    }

    private void fillTablePonuda() {
        DefaultTableModel model=new DefaultTableModel(new String[]{"Naziv", "Specifikacija", "Prodajna cena", "Dobavljac"}, 0);
        Ponuda ponuda=new Ponuda();
        List<Komponenta> komponente=ponuda.vratiSadrzajPonude();
        for (Komponenta komponenta : komponente) {
            model.addRow(new Object[]{komponenta.getNaziv(), komponenta.getSpecifikacija(), komponenta.getProdajnaCena(), komponenta.getDobavljac()});
        }
        tablePonuda.setModel(model);
    }
}
